### ISSUE TITLE
[TODO] Fix Gamepad::SetLayout

### ISSUE THREAD

**Issue by TurtleP** [TurtleP/LovePotion#55]
Currently doesn't work. Some things need to be done:

- [ ] Open all `SDL_Joystick` ptrs into Joysticks: pass the `SDL_Joystick` ptr to the Gamepad ctor
- [ ] Save the `Gamepad` object's pair ID's as an std::pair, e.g. `CONTROLLER_PLAYER_1::CONTROLLER_PLAYER_2` for Player 1 in `Dual` mode
- [ ] Save the `Gamepad` object's `SDL_Joystick` ptr to an std::pair and map `first` to the ctor value
- [ ] Inside `Gamepad::SetLayout`:
  - Close the handle for the dual mode controller
  - Delete the `SDL_Joystick` ptrs from the std::pair (or make them both nullptr?)
  - Check the "mode" and apply the proper `hid` calls to the pair values
  - If the layout is single (from dual), store the two `SDL_Joystick` ptrs into the proper std::pair
  - If the layout is dual (from single), store the single `SDL_Joystick` ptr to the proper std::pair

This should work mainly because the SDL_Joystick ptr(s) are only used within the `Gamepad` class. Calling `SDL_JoystickOpen(int which)` affects the `SDL_PollEvent` function so that each Joycon may operate properly.

[Basic example via python](https://github.com/TurtleP/LovePotion/files/2640281/MoralPerfectEngineer.zip)

**Comment by TurtleP** [comment]
Almost working, there’s just a bug with handling the controllers in SDL_Event

**Comment by TurtleP** [comment]
the thing has been done \o/

Function was renamed to `Gamepad:split(layout)` and `Gamepad:merge(gamepad)`.
`split` returns the ID of the paired controller for the Joy-Con (so for player 1, returns 2).
Use this ID to access the Gamepad reference via `love.joystick.getJoysticks()` returned table.
The optional layout argument is "horizontal" by default and can be set to "vertical" otherwise.
After calling `Gamepad:merge(other)` you must destroy the referenced gamepad obtained from the Joystick table. Anyone looking for an example, [please click here for a gist](https://gist.github.com/TurtleP/d40f1797538c6c324bf1b4c8e81f658a). The examples repository will host this file soon.
